# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
email: markrhoughton3@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my website! I hope you find what you're looking for.
  If not please don't hesitate to contact me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://m-r-houghton.github.io/" # the base hostname & protocol for your site
github_username:  M-R-Houghton

# Build settings
markdown: kramdown
